#ifndef MENU_FUELSENSOR_IRRTANK_SPLINETABLE_VIEWERNODE_H_
#define MENU_FUELSENSOR_IRRTANK_SPLINETABLE_VIEWERNODE_H_

void mFuelSensor_irrTank_spTable_viewerNode_prev(void);
void mFuelSensor_irrTank_spTable_viewerNode_next(void);
void mFuelSensor_irrTank_spTable_viewerNode_header(const char *title);
void mFuelSensor_irrTank_spTable_viewerNode_node(int8_t inode);

#endif // MENU_FUELSENSOR_IRRTANK_SPLINETABLE_VIEWERNODE_H_
