#ifndef MENU_FUELSENSOR_IRRTANK_SPLINETABLE_NEWTABLE_H_
#define MENU_FUELSENSOR_IRRTANK_SPLINETABLE_NEWTABLE_H_

void mFuelSensor_irrTank_spTable_new_job(void);
void mFuelSensor_irrTank_spTable_new_errorConsistency_job(void);
void mFuelSensor_irrTank_spTable_new_save_continue_job(void);
void mFuelSensor_irrTank_spTable_new_minNode_job(void);
void mFuelSensor_irrTank_spTable_new_maximum_size_job(void);

#endif
